name: Deploy dbt Project

# Controls when the action will run. 
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    env: 
      SNOWFLAKE_CLI_FEATURES_ENABLE_DBT: true
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_DATABASE: ${{ vars.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ vars.SNOWFLAKE_SCHEMA }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0
        with: # Ensures Snowflake CLI will search for OIDC users matching this subject
          use-oidc: true
        
      - name: Check Snowflake CLI Version
        run: snow --version

      # The -x is short hand for --temporary-connection
      - name: Test the Snowflake CLI connection
        run: snow connection test -x

      - name: List all users with OIDC federation enabled on your account
        run: snow auth oidc list -x

      - name: Deploy the dbt project object in ${{ vars.SNOWFLAKE_ACCOUNT }} on ${{ vars.SNOWFLAKE_DATABASE }}.${{ vars.SNOWFLAKE_SCHEMA }}
        run: snow dbt deploy DEMO_DBT_PROJECT --source ./tasty_bytes_dbt_demo --force -x

      - name: List all of the snowflake dbt project objects on ${{ vars.SNOWFLAKE_ACCOUNT }}
        run: snow dbt list -x

      - name: Execute run on dbt project object in ${{ vars.SNOWFLAKE_ACCOUNT }} on ${{ vars.SNOWFLAKE_DATABASE }}.${{ vars.SNOWFLAKE_SCHEMA }}
        run: snow dbt execute -x DEMO_DBT_PROJECT run --target dev

      - name: Execute data quality test on dbt project object in ${{ vars.SNOWFLAKE_ACCOUNT }} on ${{ vars.SNOWFLAKE_DATABASE }}.${{ vars.SNOWFLAKE_SCHEMA }}
        run: snow dbt execute -x DEMO_DBT_PROJECT test --target dev
